---
title: "Introduction to R"
subtitle: "Data analysis and visualization for researchers"
author: Michael Koontz and Ryan Peek
---

<br>

## Welcome

Welcome to an interactive, week-long introduction to the programming language R!

R is a powerful, cross-platform, open-source, and free software that has been widely adopted across a number of science fields. While incredibly useful, it can also be daunting to learn. This course doesn’t require any prior programming experience. We’ll teach you the basics of R by writing code together and setting up our computers the same way you will to work on your own data after the workshop. By the end of the week, you’ll be able to input, organize, and summarize data in R. You’ll also learn how to visualize and present data using publication-quality plots and dynamic documents that combine descriptive writing with the results of your code. The course will focus on laying a groundwork of basic R skills to enable future self-teaching of specific use cases.

This instance of the course is being taught as a part of the [Data Intensive Biology Summer Institute DIBSI](http://ivory.idyll.org/dibsi/toc.html) using a [Data Carpentry](http://www.datacarpentry.org/) framework. We are located in Room 2030 of the Valley Hall teaching facility on the Health Sciences side of UC Davis main campus, in Davis, CA. ([Google maps link](https://www.google.com/maps/place/Gladys+Valley+Hall,+Davis,+CA+95616/@38.5328167,-121.7659017,17z/data=!3m1!4b1!4m5!3m4!1s0x80852902c9d969a7:0xaa647225d10f76a3!8m2!3d38.5328167!4d-121.7637077)).

<br>

## Important links

**Etherpad**  
We will use this Etherpad for chatting, taking notes, and sharing URLs and bits of code.

* [http://pad.software-carpentry.org/2017-07-17-ucdavis-intro-to-R](http://pad.software-carpentry.org/2017-07-17-ucdavis-intro-to-R)  

**Live code**  
This is the live script file that we are generating throughout each day. Click "refresh" in your browser to see the latest saved version.

* [day 1](https://dl.dropboxusercontent.com/s/i86w1hk7bza03js/2017-07-17-DIBSI-intro-rstats-day1.R?dl=0)
* [day 2](https://dl.dropboxusercontent.com/s/xnx681br9aian1d/2017-07-18-DIBSI-intro-rstats-day2.R?dl=0)
* [day 3](https://dl.dropboxusercontent.com/s/jfmdgabjtdlpu86/2017-07-19-DIBSI-intro-rstats-day3.R?dl=0)
* [day 4 .R script](https://dl.dropboxusercontent.com/s/o5iwrapmta3kicj/2017-07-20-DIBSI-intro-rstats-day4.R?dl=0)
* [day 4 .Rmd script](https://dl.dropboxusercontent.com/s/y0qbpk5b2uswv8d/dplyr_ggplot_pipeline.Rmd?dl=0)
* [day 5](https://dl.dropboxusercontent.com/s/00zpp6rnrkflxyb/2017-07-21-DIBSI-intro-rstats-day5.R?dl=0)

**Feedback forms**  
These are generic Google Forms that we'll use to get immediate feedback throughout the course.

* [multiple choice question](https://goo.gl/forms/P79MCLErZVPvTGd52)
* [general feedback](https://goo.gl/forms/xYOnJJ5jS5Nsg2Yn2)

**Data Carpentry workshop surveys**
These pre- and post-workshop surveys help us ensure the effectiveness of our
teaching methodology.

* [pre-workshop survey](https://goo.gl/forms/DyiQTimFo4McSORC3)
* [post-workshop survey]()  

<br>

## Requirements

Data Carpentry's teaching is hands-on, so participants are encouraged to use
their own computers to ensure the proper setup of tools for an efficient
workflow.  *These lessons assume no prior knowledge of the skills or tools*, but
working through this lesson requires working copies of **R** and **RStudio**. A working
copy of a **spreadsheet program** is recommended, but not required.
To most effectively use these materials, please make sure to download
and install everything *before* working through this lesson. Participants are 
required to abide by Data Carpentry's [Code of Conduct](about.html#code_of_conduct).

<br>

## Setup instructions

### R and RStudio

**R** and **RStudio** are separate downloads and installations. R is the underlying statistical computing environment. RStudio is a graphical integrated development environment (IDE) that makes using R much easier and more interactive. You need to install R before you install RStudio.

#### Windows

##### If you already have R and RStudio installed

* Open RStudio, and click on "Help" > "Check for updates". If a new version is
	available, quit RStudio, and download the latest version for RStudio.
* To check which version of R you are using, start RStudio and the first thing
  that appears in the console indicates the version of R you are
  running. Alternatively, you can type `sessionInfo()`, which will also display
  which version of R you are running. Go on
  the [CRAN website](https://cran.r-project.org/bin/windows/base/) and check
  whether a more recent version is available. If so, please download and install
  it. You can [check here](https://cran.r-project.org/bin/windows/base/rw-FAQ.html#How-do-I-UNinstall-R_003f) for
  more information on how to remove old versions from your system if you wish to do so.

##### If you don't have R and RStudio installed

* Download R from
  the [CRAN website](http://cran.r-project.org/bin/windows/base/release.htm).
* Run the `.exe` file that was just downloaded
* Go to the [RStudio download page](https://www.rstudio.com/products/rstudio/download/#download)
* Under *Installers* select **RStudio x.yy.zzz - Windows
  XP/Vista/7/8** (where x, y, and z represent version numbers)
* Double click the file to install it
* Once it's installed, open RStudio to make sure it works and you don't get any
  error messages.


#### macOS

##### If you already have R and RStudio installed

* Open RStudio, and click on "Help" > "Check for updates". If a new version is
	available, quit RStudio, and download the latest version for RStudio.
* To check the version of R you are using, start RStudio and the first thing
  that appears on the terminal indicates the version of R you are running. Alternatively, you can type `sessionInfo()`, which will also display which version of R you are running. Go on
  the [CRAN website](https://cran.r-project.org/bin/macosx/) and check
  whether a more recent version is available. If so, please download and install
  it.

##### If you don't have R and RStudio installed

* Download R from
  the [CRAN website](http://cran.r-project.org/bin/macosx).
* Select the `.pkg` file for the latest R version
* Double click on the downloaded file to install R
* It is also a good idea to install [XQuartz](https://www.xquartz.org/) (needed
  by some packages)
* Go to the [RStudio download page](https://www.rstudio.com/products/rstudio/download/#download)
* Under *Installers* select **RStudio x.yy.zzz - Mac OS X 10.6+ (64-bit)**
  (where x, y, and z represent version numbers)
* Double click the file to install RStudio
* Once it's installed, open RStudio to make sure it works and you don't get any
  error messages.


#### Linux

* Follow the instructions for your distribution
  from [CRAN](https://cloud.r-project.org/bin/linux), they provide information
  to get the most recent version of R for common distributions. For most
  distributions, you could use your package manager (e.g., for Debian/Ubuntu run
  `sudo apt-get install r-base`, and for Fedora `sudo yum install R`), but we
  don't recommend this approach as the versions provided by this are
  usually out of date. In any case, make sure you have at least R 3.3.1.
* Go to the
  [RStudio download page](https://www.rstudio.com/products/rstudio/download/#download)
* Under *Installers* select the version that matches your distribution, and
  install it with your preferred method (e.g., with Debian/Ubuntu `sudo dpkg -i
  rstudio-x.yy.zzz-amd64.deb` at the terminal).
* Once it's installed, open RStudio to make sure it works and you don't get any
  error messages.
  
### Spreadsheet program

To interact with spreadsheets, we can use LibreOffice, Microsoft Excel, Gnumeric, OpenOffice.org, or other programs. Commands may differ a bit between programs, but general ideas for thinking about spreadsheets are the same.

For this lesson, if you don't have a spreadsheet program already, you can use LibreOffice. It's a free, open source spreadsheet program.

#### Windows

- Download the Installer 
  - Install LibreOffice by going to [the installation page](https://www.libreoffice.org/download/libreoffice-fresh/). The version for Windows should automatically be selected. Click Download Version X.X.X (whichever is the most recent version). You will go to a page that asks about a donation, but you don't need to make one. Your download should begin automatically.
- Install LibreOffice 
- Once the installer is downloaded, double click on it and LibreOffice should install.

#### Mac OS X

- Download the Installer 
  - Install LibreOffice by going to [the installation page](https://www.libreoffice.org/download/libreoffice-fresh/). The version for Mac should automatically be selected. Click Download Version X.X.X (whichever is the most recent version). You will go to a page that asks about a donation, but you don't need to make one. Your download should begin automatically.
- Install LibreOffice 
- Once the installer is downloaded, double click on it and LibreOffice should install.


#### Linux

- Download the Installer 
  - Install LibreOffice by going to [the installation page](https://www.libreoffice.org/download/libreoffice-fresh/). The version for Linux should automatically be selected. Click Download Version X.X.X (whichever is the most recent version). You will go to a page that asks about a donation, but you don't need to make one. Your download should begin automatically.
- Install LibreOffice 
- Once the installer is downloaded, double click on it and LibreOffice should install.

<br>

These setup instructions are adapted from those written for [Data Carpentry: R for Data Analysis and Visualization of Ecological Data](http://www.datacarpentry.org/R-ecology-lesson/) and [Data Carpentry: Data Organization in Spreadsheets](http://www.datacarpentry.org/spreadsheet-ecology-lesson/).