<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>R for reproducible scientific analysis</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/font-awesome-4.5.0/css/font-awesome.min.css" rel="stylesheet" />
<link rel="stylesheet" href="site_libs_extra/academicons-1.8.0/css/academicons.css"/>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />

</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}

.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Day 1
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="lesson_getting_started.html">Getting started</a>
    </li>
    <li>
      <a href="lesson_intro_r_rstudio.html">Orientation to programming, R, and RStudio</a>
    </li>
    <li>
      <a href="lesson_project_management.html">Project management</a>
    </li>
    <li>
      <a href="lesson_data_frames.html">Data frames</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Day 2
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="refresh_day1.html">Refresh day 1</a>
    </li>
    <li>
      <a href="lesson_dplyr.html">Data frame manipulation</a>
    </li>
    <li>
      <a href="lesson_visualization_ggplot2.html">Data visualization</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Day 3
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="refresh_day2.html">Refresh day 2</a>
    </li>
    <li>
      <a href="http://www.datacarpentry.org/spreadsheet-ecology-lesson/">Spreadsheets</a>
    </li>
    <li>
      <a href="lesson_data_import.html">Data import</a>
    </li>
    <li>
      <a href="lesson_dynamic_documents.html">Dynamic documents</a>
    </li>
    <li>
      <a href="lesson_import_dplyr_ggplot2.html">Data import %&gt;% dplyr %&gt;% ggplot2</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Day 4
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="refresh_day3.html">Refresh day 3</a>
    </li>
    <li>
      <a href="lesson_tidyr.html">Tidying data</a>
    </li>
    <li>
      <a href="lesson_lubridate.html">Time data with lubridate</a>
    </li>
    <li>
      <a href="lesson_functions.html">Custom functions</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Day 5
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="refresh_day4.html">Refresh day 4</a>
    </li>
    <li>
      <a href="lesson_joins.html">Table joins</a>
    </li>
    <li>
      <a href="lesson_for_loops.html">Automation with for loops</a>
    </li>
    <li>
      <a href="lesson_purrr.html">Automation with purrr</a>
    </li>
    <li>
      <a href="lesson_capstone.html">Capstone</a>
    </li>
    <li>
      <a href="lesson_closing_thoughts.html">Closing thoughts</a>
    </li>
  </ul>
</li>
<li>
  <a href="resources.html">Resources</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="contact.html">Contact</a>
</li>
<li>
  <a href="https://github.com/mikoontz/data-carpentry-week">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">R for reproducible scientific analysis</h1>
<h3 class="subtitle"><em>Multi-Table Joins</em></h3>

</div>


<blockquote>
<h2 id="learning-objectives" class="objectives">Learning objectives</h2>
<ul>
<li>Focus on the third tidy data principle
<ul>
<li>Each variable forms a column.</li>
<li>Each observation forms a row.</li>
<li>Each type of observational unit forms a table.</li>
</ul></li>
<li>By able to use <code>dplyr</code>’s join functions to merge tables</li>
</ul>
</blockquote>
<div id="joins" class="section level3">
<h3>Joins</h3>
<p>The third tidy data maxim states that each observation type gets its own table. The idea of multiple tables within a dataset will be familiar to anyone who has worked with a relational database but may seem foreign to those who have not.</p>
<p>The idea is this: Suppose we conduct a behavioral experiment that puts individuals in groups, and we measure both individual- and group-level variables. We should have a table for the individual-level variables and a separate table for the group-level variables. Then, should we need to merge them, we can do so using the <code>join</code> functions of <code>dplyr</code>.</p>
<p>The join functions are nicely illustrated in RStudio’s <a href="https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf">Data wrangling cheatsheet</a>. Each function takes two data.frames and, optionally, the name(s) of columns on which to match. If no column names are provided, the functions match on all shared column names.</p>
<p>The different join functions control what happens to rows that exist in one table but not the other.</p>
<ul>
<li><code>left_join</code> keeps all the entries that are present in the left (first) table and excludes any that are only in the right table.</li>
<li><code>right_join</code> keeps all the entries that are present in the right table and excludes any that are only in the left table.</li>
<li><code>inner_join</code> keeps only the entries that are present in both tables. <code>inner_join</code> is the only function that guarantees you won’t generate any missing entries.</li>
<li><code>full_join</code> keeps all of the entries in both tables, regardless of whether or not they appear in the other table.</li>
</ul>
<div class="figure">
<img src="fig/dplyr-joins.png" alt="dplyr joins, via RStudio" />
<p class="caption">dplyr joins, via RStudio</p>
</div>
<p>We will practice on our continents data.frame from module 2 and the gapminder data.frame. Note how these are tidy data: We have observations at the level of continent and at the level of country, so they go in different tables. The continent column in the gapminder data.frame allows us to link them now. If continents data.frame isn’t in your Environment, load it and recall what it consists of:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">load</span>(<span class="st">&#39;data/continents.RDA&#39;</span>)
continents</code></pre></div>
<pre><code>##    continent area_km2 population percent_total_pop
## 1     Africa 30370000 1022234000              15.0
## 2   Americas 42330000  934611000              14.0
## 3 Antarctica 13720000       4490               0.0
## 4       Asia 43820000 4164252000              60.0
## 5     Europe 10180000  738199000              11.0
## 6    Oceania  9008500   29127000               0.4</code></pre>
<p>We can join the two data.frames using any of the <code>dplyr</code> functions. We will pass the results to <code>str</code> to avoid printing more than we can read, and to get more high-level information on the resulting data.frames.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">left_join</span>(gapminder, continents) </code></pre></div>
<pre><code>## Joining, by = &quot;continent&quot;</code></pre>
<pre><code>## Warning: Column `continent` joining factor and character vector, coercing
## into character vector</code></pre>
<pre><code>## # A tibble: 1,704 x 11
##        country continent  year lifeExp      pop gdpPercap   total_gdp
##         &lt;fctr&gt;     &lt;chr&gt; &lt;int&gt;   &lt;dbl&gt;    &lt;int&gt;     &lt;dbl&gt;       &lt;dbl&gt;
##  1 Afghanistan      Asia  1952  28.801  8425333  779.4453  6567086330
##  2 Afghanistan      Asia  1957  30.332  9240934  820.8530  7585448670
##  3 Afghanistan      Asia  1962  31.997 10267083  853.1007  8758855797
##  4 Afghanistan      Asia  1967  34.020 11537966  836.1971  9648014150
##  5 Afghanistan      Asia  1972  36.088 13079460  739.9811  9678553274
##  6 Afghanistan      Asia  1977  38.438 14880372  786.1134 11697659231
##  7 Afghanistan      Asia  1982  39.854 12881816  978.0114 12598563401
##  8 Afghanistan      Asia  1987  40.822 13867957  852.3959 11820990309
##  9 Afghanistan      Asia  1992  41.674 16317921  649.3414 10595901589
## 10 Afghanistan      Asia  1997  41.763 22227415  635.3414 14121995875
## # ... with 1,694 more rows, and 4 more variables: log_gdp &lt;dbl&gt;,
## #   area_km2 &lt;dbl&gt;, population &lt;dbl&gt;, percent_total_pop &lt;dbl&gt;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">right_join</span>(gapminder, continents)</code></pre></div>
<pre><code>## Joining, by = &quot;continent&quot;</code></pre>
<pre><code>## Warning: Column `continent` joining factor and character vector, coercing
## into character vector</code></pre>
<pre><code>## # A tibble: 1,705 x 11
##    country continent  year lifeExp      pop gdpPercap    total_gdp
##     &lt;fctr&gt;     &lt;chr&gt; &lt;int&gt;   &lt;dbl&gt;    &lt;int&gt;     &lt;dbl&gt;        &lt;dbl&gt;
##  1 Algeria    Africa  1952  43.077  9279525  2449.008  22725632678
##  2 Algeria    Africa  1957  45.685 10270856  3013.976  30956113720
##  3 Algeria    Africa  1962  48.303 11000948  2550.817  28061403854
##  4 Algeria    Africa  1967  51.407 12760499  3246.992  41433235247
##  5 Algeria    Africa  1972  54.518 14760787  4182.664  61739408943
##  6 Algeria    Africa  1977  58.014 17152804  4910.417  84227416174
##  7 Algeria    Africa  1982  61.368 20033753  5745.160 115097120653
##  8 Algeria    Africa  1987  65.799 23254956  5681.359 132119742845
##  9 Algeria    Africa  1992  67.744 26298373  5023.217 132102425043
## 10 Algeria    Africa  1997  69.152 29072015  4797.295 139467033682
## # ... with 1,695 more rows, and 4 more variables: log_gdp &lt;dbl&gt;,
## #   area_km2 &lt;dbl&gt;, population &lt;dbl&gt;, percent_total_pop &lt;dbl&gt;</code></pre>
<p>These operations produce slightly different results, either 1704 or 1705 observations. Can you figure out why? Antarctica contains no countries so doesn’t appear in the gapminder data.frame. When we use <code>left_join</code> it gets filtered from the results, but when we use <code>right_join</code> it appears, with missing values for all of the country-level variables:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">right_join</span>(gapminder, continents) %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(continent ==<span class="st"> &quot;Antarctica&quot;</span>)</code></pre></div>
<pre><code>## Joining, by = &quot;continent&quot;</code></pre>
<pre><code>## Warning: Column `continent` joining factor and character vector, coercing
## into character vector</code></pre>
<pre><code>## # A tibble: 1 x 11
##   country  continent  year lifeExp   pop gdpPercap total_gdp log_gdp
##    &lt;fctr&gt;      &lt;chr&gt; &lt;int&gt;   &lt;dbl&gt; &lt;int&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
## 1      NA Antarctica    NA      NA    NA        NA        NA      NA
## # ... with 3 more variables: area_km2 &lt;dbl&gt;, population &lt;dbl&gt;,
## #   percent_total_pop &lt;dbl&gt;</code></pre>
<p>There’s another problem in this data.frame – it has two population measures, one by continent and one by country and it’s not clear which is which! Let’s rename a couple of columns.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">right_join</span>(gapminder, continents) %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">rename</span>(<span class="dt">country_pop =</span> pop, <span class="dt">continent_pop =</span> population)</code></pre></div>
<pre><code>## Joining, by = &quot;continent&quot;</code></pre>
<pre><code>## Warning: Column `continent` joining factor and character vector, coercing
## into character vector</code></pre>
<pre><code>## # A tibble: 1,705 x 11
##    country continent  year lifeExp country_pop gdpPercap    total_gdp
##     &lt;fctr&gt;     &lt;chr&gt; &lt;int&gt;   &lt;dbl&gt;       &lt;int&gt;     &lt;dbl&gt;        &lt;dbl&gt;
##  1 Algeria    Africa  1952  43.077     9279525  2449.008  22725632678
##  2 Algeria    Africa  1957  45.685    10270856  3013.976  30956113720
##  3 Algeria    Africa  1962  48.303    11000948  2550.817  28061403854
##  4 Algeria    Africa  1967  51.407    12760499  3246.992  41433235247
##  5 Algeria    Africa  1972  54.518    14760787  4182.664  61739408943
##  6 Algeria    Africa  1977  58.014    17152804  4910.417  84227416174
##  7 Algeria    Africa  1982  61.368    20033753  5745.160 115097120653
##  8 Algeria    Africa  1987  65.799    23254956  5681.359 132119742845
##  9 Algeria    Africa  1992  67.744    26298373  5023.217 132102425043
## 10 Algeria    Africa  1997  69.152    29072015  4797.295 139467033682
## # ... with 1,695 more rows, and 4 more variables: log_gdp &lt;dbl&gt;,
## #   area_km2 &lt;dbl&gt;, continent_pop &lt;dbl&gt;, percent_total_pop &lt;dbl&gt;</code></pre>
<blockquote>
<h4 id="challenge-putting-the-pieces-together" class="challenge">Challenge – Putting the pieces together</h4>
<p>A colleague suggests that the more land area an individual has, the greater their gdp will be and that this relationship will be observable at any scale of observation. You chuckle and mutter “Not at the continental scale,” but your colleague insists. Test your colleague’s hypothesis by:</p>
<ul>
<li>Calculating the total GDP of each continent,
<ul>
<li>Hint: Use <code>dplyr</code>’s <code>group_by</code> and <code>summarize</code></li>
</ul></li>
<li>Joining the resulting data.frame to the <code>continents</code> data.frame,</li>
<li>Calculating the per-capita GDP for each continent, and</li>
<li>Plotting per-capita gdp versus population density.</li>
</ul>
</blockquote>
</div>
<div id="challenge-solutions" class="section level2">
<h2>Challenge solutions</h2>
<blockquote>
<h4 id="solution-to-challenge-putting-the-pieces-together" class="challenge">Solution to Challenge – Putting the pieces together</h4>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)

<span class="co"># Calculate country-level GDP</span>
<span class="kw">mutate</span>(gapminder, <span class="dt">GDP =</span> gdpPercap *<span class="st"> </span>pop) %&gt;%<span class="st">  </span>
<span class="co"># Group by continent</span>
<span class="st">    </span><span class="kw">group_by</span>(continent) %&gt;%<span class="st">  </span>
<span class="co"># Calculate continent-level GDP</span>
<span class="st">    </span><span class="kw">summarize</span>(<span class="dt">cont_gdp =</span> <span class="kw">sum</span>(GDP)) %&gt;%<span class="st">  </span>
<span class="co"># Join the continent-GDP data.frame to the continents data.frame</span>
<span class="st">    </span><span class="kw">left_join</span>(continents) %&gt;%<span class="st">  </span>
<span class="co"># Calculate continent-level per-capita GDP</span>
<span class="st">    </span><span class="kw">mutate</span>(<span class="dt">per_cap =</span> cont_gdp /<span class="st"> </span>population) %&gt;%<span class="st">  </span>
<span class="co"># Plot gdp versus land area</span>
<span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> area_km2, <span class="dt">y =</span> per_cap)) +<span class="st">  </span>
<span class="co"># Draw points</span>
<span class="st">    </span><span class="kw">geom_point</span>() +<span class="st">  </span>
<span class="co"># And label them</span>
<span class="st">    </span><span class="kw">geom_text</span>(<span class="kw">aes</span>(<span class="dt">label =</span> continent), <span class="dt">nudge_y =</span> <span class="fl">5e3</span>)  </code></pre></div>
<pre><code>## Joining, by = &quot;continent&quot;</code></pre>
<pre><code>## Warning: Column `continent` joining factor and character vector, coercing
## into character vector</code></pre>
<p><img src="lesson_joins_files/figure-html/Putting%20the%20pieces%20together%20-%20solution-1.png" width="672" /></p>
</blockquote>
<p><br></p>
<p>This lesson is adapted from the Software Carpentry: R for Reproducible Scientific Analysis <a href="http://data-lessons.github.io/gapminder-R/12-joins.html">Multi-Table Joins materials</a>.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
