---
title: "Resources"
---

<br>

## Datasets

Here are handy links to all of the data sets used in the course that we can't
get through packages.

* From [The Portal Project Teaching Database](https://doi.org/10.6084/m9.figshare.1314459.v6)
    + [Portal_rodents_19772002_scinameUUIDs.csv](data/Portal_rodents_19772002_scinameUUIDs.csv) [raw trapping data]
    + [species.csv](data/species.csv) [species id metadata]
    + [surveys.csv](data/surveys.csv) [trapping data by record id]
    + [combined.csv](data/combined.csv) [trapping data merged with record id metadata]
    + [plots.csv](data/plots.csv) [plot type metadata]
* From [Data Carpentry: Genomics Lesson](https://jasonjwilliamsny.github.io/tidiness-genomics/)
    + [sequencing_results_metadata.txt](data/sequencing_results_metadata.txt) [metadata from DNA sequencing]
* From [Data Carpentry: R for Data Analysis and Visualization of Ecological Data](http://www.datacarpentry.org/R-ecology-lesson/)
    + [survey_data_spreadsheet_messy.xls](data/survey_data_spreadsheet_messy.xls) [example of untidy data]
* From [Software Carpentry: R for Reproducible Scientific Analysis](http://data-lessons.github.io/gapminder-R/)
    + [continents.RDA](data/continents.RDA) [gapminder continent-level data]
    + [wide_eg.csv](data/wide_eg.csv) [blood albumin levels]
    + [stocks.tsv](data/stocks.tsv) [restaurant stock data]
    + [gapminder.csv](data/gapminder.csv) [country characteristics by year]
* From [Ethan White and Zack Brym's Data Carpentry for Biologists course](http://www.datacarpentry.org/semester-biology/)

<br>

## Course content

For this course, we embrace the spirit of [collaborative lesson development](https://arxiv.org/abs/1707.02662). We leverage the community's effort to develop effective approaches to teach this material using modern educational psychology and instructional design, and draw lessons from the following open sources:

* [Software Carpentry: R for Reproducible Scientific Analysis](http://data-lessons.github.io/gapminder-R/)
* [Data Carpentry: R for Data Analysis and Visualization of Ecological Data](http://www.datacarpentry.org/R-ecology-lesson/)
* [Data Carpentry: Data Organization in Spreadsheets](http://www.datacarpentry.org/spreadsheet-ecology-lesson/)
* [Data Carpentry: Genomics Lesson](https://jasonjwilliamsny.github.io/tidiness-genomics/)
* [Ethan White and Zack Brym's Data Carpentry for Biologists course](http://www.datacarpentry.org/semester-biology/)
* [Ryan Peek's Data wRangling for Ecologists course](https://gge-ucd.github.io/wRangling-Ecology/)
* [Jenny Bryan's Stat545 course](http://stat545.com/)
* [Chester Ismay and Albert Y. Kim's Modern DiveR book](https://ismayc.github.io/moderndiver-book/)
* [Michael Koontz's Introduction to R course](http://introtor.weebly.com/)

<br>

## Extra readings

* [Tidy Data paper by Hadley Wickham in the Journal of Statistical Software (2014)](https://www.jstatsoft.org/article/view/v059i10)
* [R for Data Science book by Garrett Grolemund and Hadley Wickham](http://r4ds.had.co.nz/)
* [RStudio Cheatsheets](https://www.rstudio.com/resources/cheatsheets/)